version: "3.8"
services:

  # PHP Service
  web:
    container_name: cas_admin
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    user: 1000:1000
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/cas_admin
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: cas
      DB_USERNAME: root
      DB_PASSWORD: password
    restart: unless-stopped

  # MYSQL Service
  mysql:
    container_name: cas_mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cas
      MYSQL_USER: cas
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped

  # PHPMyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    restart: unless-stopped
